dist: xenial

language: go

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

env:
  - GO111MODULE=on

go:
  - 1.14.x

git:
  depth: 1

install: true

notifications:
  email: false

before_script:
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - golangci-lint run
  - go test -race -coverprofile=coverage.out -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
